"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.10.
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# -------------------------
# Local .env loader (Manually loads secrets from .env file)
# -------------------------
def _load_dotenv(dotenv_path: Path) -> None:
    try:
        if not dotenv_path.exists():
            return
        for raw_line in dotenv_path.read_text(encoding="utf-8").splitlines():
            line = raw_line.strip()
            if not line or line.startswith("#") or "=" not in line:
                continue
            k, v = line.split("=", 1)
            key = k.strip()
            val = v.strip().strip('"').strip("'")
            if key:
                os.environ.setdefault(key, val)
    except Exception:
        # If .env is malformed, don't crash settings import.
        return

# Load the .env file from the root directory
_load_dotenv(BASE_DIR / ".env")


# Quick-start development settings - unsuitable for production
SECRET_KEY = 'django-insecure-&17+vb=wkt)4!r8%j&lmq9c@e)0n^&1yj!kq1@%spgps4-pqh2'
DEBUG = True
ALLOWED_HOSTS = ["*"]


# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',  # Required for React connection
    'SafeTrip_API', # Your main app
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',  # Must be at the top
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
STATIC_URL = 'static/'

# Media uploads (profile images)
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Use the custom user model defined in SafeTrip_API.models
AUTH_USER_MODEL = 'SafeTrip_API.customUser'    


# -------------------------
# CORS SETTINGS (Connect to React)
# -------------------------
CORS_ALLOW_ALL_ORIGINS = True  # Allows any frontend to connect (Good for Hackathon)


# -------------------------
# EMAIL CONFIGURATION (Gmail)
# -------------------------
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True

# Load these directly from environment variables (populated by _load_dotenv above)
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD')

# Fallback: If no password is found, print emails to console instead of crashing
if not EMAIL_HOST_PASSWORD:
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
    print("\n⚠️ WARNING: No Email Password found. Emails will be printed to console.\n")

# Recipients for emergency alert emails (comma-separated).
# Example in .env:
#   AUTHORITY_ALERT_EMAILS=police@example.com,ambulance@example.com
_authority_raw = os.environ.get("AUTHORITY_ALERT_EMAILS", "")
AUTHORITY_ALERT_EMAILS = [e.strip() for e in _authority_raw.split(",") if e.strip()]

# Hackathon-friendly fallback: if none set, send to the configured sender address
if not AUTHORITY_ALERT_EMAILS and EMAIL_HOST_USER:
    AUTHORITY_ALERT_EMAILS = [EMAIL_HOST_USER]


# -------------------------
# OTP & CACHE SETTINGS
# -------------------------
# Cache is required to store OTPs. LocMemCache is fine for hackathon/dev.
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'safetrip-otp-cache',
    }
}

OTP_LENGTH = 6
OTP_TTL_SECONDS = 300  # 5 minutes
OTP_MAX_VERIFY_ATTEMPTS = 5
OTP_MAX_SENDS_PER_WINDOW = 3
OTP_SEND_WINDOW_SECONDS = 600  # 10 minutes