# Generated by Cursor on 2026-01-31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("SafeTrip_API", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="OTPStorage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("email", models.EmailField(db_index=True, max_length=254)),
                ("otp", models.CharField(max_length=10)),
                ("counter", models.PositiveIntegerField(default=1)),
                ("is_expired", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]

