# Generated by Django 5.2.10 on 2026-01-31 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SafeTrip_API', '0003_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='emergency_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
    ]
