# Generated by Django 5.1.6 on 2026-01-31 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SafeTrip_API', '0005_emergencyalert'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('USER', 'User'), ('AUTHORITY', 'Authority')], default='USER', max_length=20),
        ),
    ]
